# Generated by Django 3.2.21 on 2024-09-03 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AISData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vessel_name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('speed', models.FloatField()),
                ('course', models.FloatField()),
                ('timestamp', models.DateTimeField()),
                ('anomaly_detected', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SARData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sar_images/')),
                ('detected_spill', models.BooleanField(default=False)),
                ('ais_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detection.aisdata')),
            ],
        ),
    ]
